openapi: 3.0.1
info:
  title: SalesAPI
  description: API Definition of SalesAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/sales
paths:
  /:
    get:
      parameters:
      - name: customerId
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
